language: java
notifications:
  hipchat:
    rooms:
      secure: oEJ+AZVMxuhGqAWiv/mII6P3iG13tOjS18zfb5ywNNbuNfm+8oT3OO9LOVqOxb1pqYP8f3WZZgWYV1dDOG5S97z9z7BPU9k4QYCjZSRlUQ+ZXNhehfpiSrls9N4ZhPdY+ulFThU7MUHdkWx54AnU1K6qqmOcHVYMSqKk7vn22n9eqb02VqydxmmR7OVgnn2pANNe9++tFuZZzRgkJ4olNJa2I9o30Xh0+BjdIPZijIee98rN24SuY+T9eyJzsUEIDA5TgfIkGw5SilGA0pL9xSMmJR62w6IGsDtRRtLCoXKp1fseq6wdDBUlnnHN3AmW2bHOFuQ75cfGmUkcyb4itaPYmcVcTRAW4hJMb6F9bGT4XKy3tZWJmFUkQCuNKl0pwVNg/aJsHuBzITm7xztX/c18SN2WK49zWAi//dT8zDnaG4L1hKvKlRmH+cMr1CujD6mBIFfOFiK8ePU6TUS5LoGjIApxmejpdflfvzu5Pa1byaKPxgdm3BQY68AQegQk3h1K7oVH23UB3U1TS9fBjKkC4Y0sUSiZzo4KDin1+vnadw+D4bKpc9vw9h3iGYLy+jois7WOq5qxfW/ohzDkwgjd87GgcH4WSBLWAPodsZp6HwemsJOZq6t8H/aLjkaPv07OsguQ9xM3u2obMucXrIYnAusENw0HNEUo8bZOy0M=
deploy:
  provider: releases
  api_key:
    secure: kngwo2bkgPVRprd3N9/khU/2VRC9f4zWgYGYhaWI5JK9owFoG8bPt6emZdt6hdIoS8yx6CcL1ZvAOASkru0j6oJkAvHln/Nmb+tTY5csnN2tcvVfOlj9CvBY1xQl2hhq7xX68jm+xvFMExPgvLy2AL3FUyyfJLZFM7eph26BNtczhG+8bBuO7164otUHxA5M0VbmekOQJXH8qGKTth/GRYuP2+H3zIaMq4j+1byAkrjFZVszYgLZoMx7s3bROTRb5Q6VRkl+07kg6BvXC8IPV/wqVRn7/TFmUHeFVE6D6JPLpW/PUkXisX2c4fwCXt/xW9n8HFBWT//F/vXpYXQKR7OBz5z3bsXfmOdM2ZOuK5O+AFRKnS56Yx86qbnqb1DfibwcKkqFwPq56jrD7FYDmT/2G+heytQXpE+taBMgZtgk9hK60zlRWJxx2hHrLGEbsZ81Cpw8TLTtPqEfpep7ji5BHs+O9vNhntqXNOBBWdl0bJbwRJWbVBnSF4BRhgej4Kg68nkp3sK9P1X85iXzWDjcFUXG38cCDNUwuJTrh1J/AY4/GHwOj6SzCMJQ86fyqXeoNg7qREAZxANw1Wyoc1hxyAEnNsJl0Ub7DDgZv3HrolBq8TsvFj/OJ4eLdgh5Sl6A6Lf3juvNqCf1TOK4L1c1kR6u94tPhTUOpDX3W7Q=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-jenkins2-plugin
