language: java
notifications:
  slack:
    secure: r05ehYmuEqAKz8dpQIEDo18re31LaweN22QITCIKiLjiVfqQtNx3FD963PiKVZCt8sDyhCbyWoBcsspwHpdXvSfbtMP9UhZRrWSBpTHScGUDBr6ZHX2JXuz1sMtT9UEaTrLJs1cyLXA7aOZFPgzxrsKLJqksv5iA/WUuI35VSsElmyZNGS44ORVDQM//wFWnzJbZvwEpzKiCF+tOSE8lh1P8CO3cjzaO0tzYnzkkLhcjDbMv/DXnyts/JLRsDDlDy0rReaEulaaaK2l2PGzekB/WSwINfpHxP2jUCwCDAE1LSvMJXKCcYDZDE0cokFxzbfeLrcwNmoEmsnznPSUGZpOCvGpb2KL5nKYMPHuwrymCTustVShw/Rigm4GgbX4iBqgCGXT+tL1CHCqlS05TTfq/+G8lYP/FT1maR9Ctl6Hhn9JVZorH7hcjBDRwdAf1ym/mjhuJTZ59gR9lP/uOETvQyLM3c5DgCCHzO6itjABLiZVYlUZj3yBX/V7QPD5yVXYIFRrV7fjDtmbQb2abRz2RPSR8JYzD6D6mm6N92P2zwt5+hMl86mhVAnHC9Qk/deTlJuB6wDkzLs7nBwTEc8j6f1fB8ltYKtWDznSZhoJZ11XJ2CcFZTzrpQF0thahm/+nyO4BJ/UPAErS5Q0LKSJtQnWRPOLndJZl+bSxrNo=
deploy:
  provider: releases
  api_key:
    secure: kngwo2bkgPVRprd3N9/khU/2VRC9f4zWgYGYhaWI5JK9owFoG8bPt6emZdt6hdIoS8yx6CcL1ZvAOASkru0j6oJkAvHln/Nmb+tTY5csnN2tcvVfOlj9CvBY1xQl2hhq7xX68jm+xvFMExPgvLy2AL3FUyyfJLZFM7eph26BNtczhG+8bBuO7164otUHxA5M0VbmekOQJXH8qGKTth/GRYuP2+H3zIaMq4j+1byAkrjFZVszYgLZoMx7s3bROTRb5Q6VRkl+07kg6BvXC8IPV/wqVRn7/TFmUHeFVE6D6JPLpW/PUkXisX2c4fwCXt/xW9n8HFBWT//F/vXpYXQKR7OBz5z3bsXfmOdM2ZOuK5O+AFRKnS56Yx86qbnqb1DfibwcKkqFwPq56jrD7FYDmT/2G+heytQXpE+taBMgZtgk9hK60zlRWJxx2hHrLGEbsZ81Cpw8TLTtPqEfpep7ji5BHs+O9vNhntqXNOBBWdl0bJbwRJWbVBnSF4BRhgej4Kg68nkp3sK9P1X85iXzWDjcFUXG38cCDNUwuJTrh1J/AY4/GHwOj6SzCMJQ86fyqXeoNg7qREAZxANw1Wyoc1hxyAEnNsJl0Ub7DDgZv3HrolBq8TsvFj/OJ4eLdgh5Sl6A6Lf3juvNqCf1TOK4L1c1kR6u94tPhTUOpDX3W7Q=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-jenkins2-plugin
